apiVersion: v1
kind: Service
metadata:
  name: tracking-order-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 83
      targetPort: 3000
      nodePort: 30083
